services:
  jaeger-agent:
    image: jaegertracing/all-in-one:1.48
    command: ["--memory.max-traces=50000"]
    ports:
      - "${JAEGER_HTTP_PORT:-16686}:16686"
      - "${JAEGER_UDP_PORT:-6831}:6831/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      default:
        aliases:
          - jaeger
          - jaeger-agent
